import { describe, it, expect } from 'vitest';
import { formatReviewAsGitLabMR, formatDocReviewAsGitLabMR } from '../../../../src/cli/formatters/gitlab.js';
import type { CodeReviewResult } from '../../../../src/agents/code-reviewer.js';

describe('formatReviewAsGitLabMR()', () => {
  const sampleResult: CodeReviewResult = {
    summary: 'Code needs security hardening',
    findings: [
      { severity: 'critical', file: 'src/db.ts', line: 10, message: 'Unescaped input', suggestion: 'Sanitize input' },
      { severity: 'suggestion', file: 'src/main.ts', line: null, message: 'Consider adding logging', suggestion: null },
    ],
    overallScore: 5,
  };

  it('마크다운 헤더에 스코어를 포함한다', () => {
    const md = formatReviewAsGitLabMR(sampleResult);
    expect(md).toContain('## Code Review (Score: 5/10)');
  });

  it('이모지 아이콘을 사용한다 (GitHub PR 포맷과 다름)', () => {
    const md = formatReviewAsGitLabMR(sampleResult);
    expect(md).toContain('🔴 CRITICAL');
    expect(md).toContain('💡 SUGGESTION');
  });

  it('파일:라인 참조를 포함한다', () => {
    const md = formatReviewAsGitLabMR(sampleResult);
    expect(md).toContain('`src/db.ts:10`');
  });

  it('JunFlow 서명을 포함한다', () => {
    const md = formatReviewAsGitLabMR(sampleResult);
    expect(md).toContain('Generated by JunFlow');
  });
});

describe('formatDocReviewAsGitLabMR()', () => {
  it('문서 리뷰를 GitLab MR 형식으로 포맷한다', () => {
    const md = formatDocReviewAsGitLabMR(
      'Needs more detail',
      6,
      [{ severity: 'warning', section: 'Design', message: 'Missing diagrams' }],
      ['Testing strategy'],
      ['Deployment plan?'],
    );

    expect(md).toContain('## Document Review (Score: 6/10)');
    expect(md).toContain('🟡 **[Design]** Missing diagrams');
    expect(md).toContain('Testing strategy');
    expect(md).toContain('Deployment plan?');
  });
});
