import { describe, it, expect } from 'vitest';
import { formatReviewAsGitHubPR, formatDocReviewAsGitHubPR } from '../../../../src/cli/formatters/markdown.js';
import type { CodeReviewResult } from '../../../../src/agents/code-reviewer.js';

describe('formatReviewAsGitHubPR()', () => {
  const sampleResult: CodeReviewResult = {
    summary: 'Overall clean code with a few security concerns',
    findings: [
      { severity: 'critical', file: 'src/auth.ts', line: 42, message: 'SQL injection risk', suggestion: 'Use parameterized queries' },
      { severity: 'warning', file: 'src/api.ts', line: 15, message: 'Missing rate limiting', suggestion: null },
      { severity: 'praise', file: 'src/utils.ts', line: null, message: 'Excellent error handling', suggestion: null },
    ],
    overallScore: 6,
  };

  it('마크다운 헤더에 스코어를 포함한다', () => {
    const md = formatReviewAsGitHubPR(sampleResult);
    expect(md).toContain('## Code Review (Score: 6/10)');
  });

  it('서머리를 포함한다', () => {
    const md = formatReviewAsGitHubPR(sampleResult);
    expect(md).toContain('Overall clean code with a few security concerns');
  });

  it('severity별 섹션을 생성한다', () => {
    const md = formatReviewAsGitHubPR(sampleResult);
    expect(md).toContain(':x: CRITICAL (1)');
    expect(md).toContain(':warning: WARNING (1)');
    expect(md).toContain(':white_check_mark: PRAISE (1)');
  });

  it('파일:라인 코드 참조를 포함한다', () => {
    const md = formatReviewAsGitHubPR(sampleResult);
    expect(md).toContain('`src/auth.ts:42`');
    expect(md).toContain('`src/api.ts:15`');
  });

  it('라인 없는 파일은 파일명만 표시한다', () => {
    const md = formatReviewAsGitHubPR(sampleResult);
    expect(md).toContain('`src/utils.ts`');
  });

  it('suggestion을 blockquote로 표시한다', () => {
    const md = formatReviewAsGitHubPR(sampleResult);
    expect(md).toContain('> Use parameterized queries');
  });

  it('JunFlow 서명을 포함한다', () => {
    const md = formatReviewAsGitHubPR(sampleResult);
    expect(md).toContain('Generated by [JunFlow]');
  });

  it('빈 findings도 처리한다', () => {
    const empty: CodeReviewResult = { summary: 'Perfect', findings: [], overallScore: 10 };
    const md = formatReviewAsGitHubPR(empty);
    expect(md).toContain('## Code Review (Score: 10/10)');
    expect(md).not.toContain('CRITICAL');
  });
});

describe('formatDocReviewAsGitHubPR()', () => {
  it('문서 리뷰를 마크다운으로 포맷한다', () => {
    const md = formatDocReviewAsGitHubPR(
      'Good structure',
      8,
      [{ severity: 'suggestion', section: 'API', message: 'Add examples', suggestion: 'Include curl examples' }],
      ['Error codes'],
      ['What about versioning?'],
    );

    expect(md).toContain('## Document Review (Score: 8/10)');
    expect(md).toContain('### Findings');
    expect(md).toContain('**[API]** Add examples');
    expect(md).toContain('### Missing Topics');
    expect(md).toContain('Error codes');
    expect(md).toContain('### Key Questions');
    expect(md).toContain('What about versioning?');
  });

  it('빈 섹션은 생략한다', () => {
    const md = formatDocReviewAsGitHubPR('Clean', 10, [], [], []);
    expect(md).not.toContain('### Findings');
    expect(md).not.toContain('### Missing Topics');
    expect(md).not.toContain('### Key Questions');
  });
});
