import type { CodeReviewResult, ReviewFinding } from '../../agents/code-reviewer.js';

const SEVERITY_ICON: Record<ReviewFinding['severity'], string> = {
  critical: '🔴',
  warning: '🟡',
  suggestion: '💡',
  praise: '✅',
};

export function formatReviewAsGitLabMR(result: CodeReviewResult): string {
  const lines: string[] = [];

  lines.push(`## Code Review (Score: ${result.overallScore}/10)`);
  lines.push('');
  lines.push(result.summary);
  lines.push('');

  const grouped: Partial<Record<ReviewFinding['severity'], ReviewFinding[]>> = {};
  for (const f of result.findings) {
    if (!grouped[f.severity]) grouped[f.severity] = [];
    grouped[f.severity]!.push(f);
  }

  for (const severity of ['critical', 'warning', 'suggestion', 'praise'] as const) {
    const items = grouped[severity];
    if (!items || items.length === 0) continue;

    const icon = SEVERITY_ICON[severity];
    lines.push(`### ${icon} ${severity.toUpperCase()} (${items.length})`);
    lines.push('');

    for (const f of items) {
      const location = f.line ? `\`${f.file}:${f.line}\`` : `\`${f.file}\``;
      lines.push(`- ${location}: ${f.message}`);
      if (f.suggestion) {
        lines.push(`  > ${f.suggestion}`);
      }
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('_Generated by JunFlow_');

  return lines.join('\n');
}

export function formatDocReviewAsGitLabMR(
  summary: string,
  score: number,
  findings: Array<{ severity: string; section: string; message: string; suggestion?: string }>,
  missingTopics: string[],
  keyQuestions: string[],
): string {
  const lines: string[] = [];

  lines.push(`## Document Review (Score: ${score}/10)`);
  lines.push('');
  lines.push(summary);
  lines.push('');

  if (findings.length > 0) {
    lines.push('### Findings');
    lines.push('');
    for (const f of findings) {
      const icon = SEVERITY_ICON[f.severity as ReviewFinding['severity']] ?? '❓';
      lines.push(`- ${icon} **[${f.section}]** ${f.message}`);
      if (f.suggestion) {
        lines.push(`  > ${f.suggestion}`);
      }
    }
    lines.push('');
  }

  if (missingTopics.length > 0) {
    lines.push('### Missing Topics');
    for (const t of missingTopics) {
      lines.push(`- ${t}`);
    }
    lines.push('');
  }

  if (keyQuestions.length > 0) {
    lines.push('### Key Questions');
    for (const q of keyQuestions) {
      lines.push(`- ${q}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('_Generated by JunFlow_');

  return lines.join('\n');
}
